<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pejabat;
use Illuminate\Support\Facades\DB;

class PejabatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $pejabats = [
            [
                'kategori_pejabat' => 'Bupati',
                'nama' => 'Lukman Hakim, S.IP., M.H',
                'jabatan_keterangan' => 'Bupati Bangkalan',
                'instansi' => 'Bupati Bangkalan',
                'tempat_lahir' => 'Bangkalan',
                'tanggal_lahir' => '1980-10-20',
                'riwayat_pendidikan' => "S-2 Universitas Trunojoyo Madura\nS-1 Universitas Muhammadiyah Malang\nSMA MAN Rejoso Paterongan\nSMP Negeri Geger\nSDN Katol Barat 2",
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/1.jpg',
            ],
            [
                'kategori_pejabat' => 'Wakil Bupati',
                'nama' => "Moch. Fauzan Dja'far, S.Ag., S.H., M.H.",
                'jabatan_keterangan' => 'Wakil Bupati Bangkalan',
                'instansi' => 'Wakil Bupati Bangkalan',
                'tempat_lahir' => 'Bangkalan',
                'tanggal_lahir' => '1978-10-11',
                'riwayat_pendidikan' => "S-2 Universitas Trunojoyo Madura\nS-1 IAIN Sunan Ampel Surabaya\nS-1 Universitas Kartina Surabaya\nMA. Manba'ul Hikam\nMTs. Manba'ul Hikam\nSDN Basanah",
                'riwayat_karir' => "Bidang Kaderisasi PMII Kom. IAIN Sunan Ampel Surabaya (1998)\nSekretaris PC. Gerakan Pemuda Ansor Kab. Bangkalan (2008)\nWakil Sekretaris PW. Gerakan Pemuda Ansor Jawa Timur (2019)\nSekretaris KNPI Kabupaten Bangkalan (2008)\nKetua KONI Kabupaten Bangkalan (2019)",
                'penghargaan' => "Madura Award Kategori Tokoh Penggerak Olahraga - Jawa Pos Radar Madura (2021)",
                'foto' => 'pejabat_fotos/2.jpg',
            ],
            [
                'kategori_pejabat' => 'Sekda',
                'nama' => 'ISMET EFFENDI, S.SOS,.M.M',
                'nip' => '196812201988091001',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Sekretaris Daerah Kab.Bangkalan',
                'instansi' => 'Sekretaris Daerah Kab.Bangkalan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/3.jpg',
            ],
            [
                'kategori_pejabat' => 'Asisten',
                'nama' => 'ANANG YULIANTO HARIPURNOMO, AP., MM.',
                'nip' => '197607141994121001',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Asisten Pemerintahan dan Kesejahteraan Rakyat Sekretariat Daerah',
                'instansi' => 'Asisten Pemerintahan dan Kesejahteraan Rakyat Sekretariat Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/4.jpg',
            ],
            [
                'kategori_pejabat' => 'Asisten',
                'nama' => 'EKO SETIAWAN, S.Si., MT.',
                'nip' => '197511212003121003',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Asisten Perekonomian dan Pembangunan Sekretariat Daerah',
                'instansi' => 'Asisten Perekonomian dan Pembangunan Sekretariat Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/5.jpg',
            ],
            [
                'kategori_pejabat' => 'Asisten',
                'nama' => 'DRA.R. AMINA RACHMAWATI, M.Si.',
                'nip' => '196707131988092001',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Asisten Administrasi Umum Sekretariat Daerah',
                'instansi' => 'Asisten Administrasi Umum Sekretariat Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/6.jpg',
            ],
            [
                'kategori_pejabat' => 'Staf Ahli',
                'nama' => 'ZAKARIYA, SH., MM.',
                'nip' => '196605021993031012',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Staf Ahli Bupati Bidang Pemerintahan, Hukum dan Politik',
                'instansi' => 'Staf Ahli Bupati Bidang Pemerintahan, Hukum dan Politik',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/7.jpg',
            ],
            [
                'kategori_pejabat' => 'Staf Ahli',
                'nama' => 'NUR HOTIBAH, S.ST.Bd., M.Mkes',
                'nip' => '1970007091991022001',
                'jabatan_keterangan' => 'Staf Ahli Bupati Bidang Kemasyarakatan dan Sumber Daya Manusia',
                'instansi' => 'Staf Ahli Bupati Bidang Kemasyarakatan dan Sumber Daya Manusia',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/8.jpg',
            ],
            [
                'kategori_pejabat' => 'Staf Ahli',
                'nama' => 'Dr. BAMBANG BUDI MUSTIKA, S.Pd., M.Pd.',
                'nip' => '196706011986031002',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Staf Ahli Bupati Bidang Ekonomi, Keuangan dan Pembangunan',
                'instansi' => 'Staf Ahli Bupati Bidang Ekonomi, Keuangan dan Pembangunan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/9.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'ZAINAL ALIM.,S.H., M.M.',
                'nip' => '196909172001121002',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'jabatan_keterangan' => 'Kepala Dinas Komunikasi dan Informatika',
                'instansi' => 'Kepala Dinas Komunikasi dan Informatika',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/10.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'RIZAL MARDIANSYAH, ST., MT.',
                'nip' => '197803202002121003',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Kepala Dinas Pekerjaan Umum dan Perumahan Rakyat',
                'instansi' => 'Kepala Dinas Pekerjaan Umum dan Perumahan Rakyat',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/11.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'WIBAGIO SUHARTA, S.Sos., MM.',
                'nip' => '197301261993021001',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Badan Perencanaan Pembangunan, Riset, dan Inovasi Daerah',
                'instansi' => 'Kepala Badan Perencanaan Pembangunan, Riset, dan Inovasi Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/12.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'H. SUDIYO, S.Kep. Ns. MM.',
                'nip' => '196609101987031008',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Keluarga Berencana, Pemberdayaan Perempuan, dan Perlindungan Anak',
                'instansi' => 'Kepala Dinas Keluarga Berencana, Pemberdayaan Perempuan, dan Perlindungan Anak',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/13.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'ABDUL AZIS, S.Si.',
                'nip' => '197001051989031003',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Kepala Dinas Sosial',
                'instansi' => 'Kepala Dinas Sosial',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/14.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Badan',
                'nama' => 'AKHMAD AHADIYAN H, S.STP., M.M.',
                'nip' => '198401152003121002',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Kepala Badan Pendapatan Daerah',
                'instansi' => 'Kepala Badan Pendapatan Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/15.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'MOHAMMAD RASULI, S.Sos., MM.',
                'nip' => '198307142001121002',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Dinas Koperasi, Usaha Kecil dan Menengah, serta Perdagangan',
                'instansi' => 'Dinas Koperasi, Usaha Kecil dan Menengah, serta Perdagangan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/16.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'ACHMAD SIDDIK, S.AP., M.M.',
                'nip' => '197002052003121004',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Plt. Kepala Dinas Lingkungan Hidup',
                'instansi' => 'Plt. Kepala Dinas Lingkungan Hidup',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/17.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'Dr. CHK Karyadinata, S.Pt., M.E.',
                'nip' => null,
                'jabatan_keterangan' => 'Plt. Kepala Dinas Pertanian, Perikanan dan Ketahanan Pangan',
                'instansi' => 'Plt. Kepala Dinas Pertanian, Perikanan dan Ketahanan Pangan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/18.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'ABDUL AZIS, S.H.',
                'nip' => '197001051989031003',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Kepala Dinas Pemberdayaan Masyarakat dan Desa',
                'instansi' => 'Kepala Dinas Pemberdayaan Masyarakat dan Desa',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/19.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'Drs. BAMBANG SETYAWAN, M.M',
                'nip' => '197109061992021003',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Kependudukan dan Pencatatan Sipil',
                'instansi' => 'Kepala Dinas Kependudukan dan Pencatatan Sipil',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/20.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'MOAWI ARIFIN, S.STP., M.M.',
                'nip' => '198002121998101001',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Pemuda dan Olahraga',
                'instansi' => 'Kepala Dinas Pemuda dan Olahraga',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/21.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'H. MOHAMMAD FAISOL S.STP., M.M.',
                'nip' => '198307142001121002',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Perhubungan',
                'instansi' => 'Kepala Dinas Perhubungan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/22.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'Ir. ISKANDAR AHADIYAT, M.M.',
                'nip' => '196610161997031003',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Kepala Dinas Peternakan & Kesehatan Hewan',
                'instansi' => 'Kepala Dinas Peternakan & Kesehatan Hewan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/23.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Badan',
                'nama' => 'ZAINUL GOMAR',
                'nip' => null,
                'jabatan_keterangan' => 'Kepala Badan Penanggulangan Bencana Daerah',
                'instansi' => 'Kepala Badan Penanggulangan Bencana Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/24.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'AKHMAD RONIYUN HAMID, ST., MM.',
                'nip' => '197311302002121005',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Perumahan Rakyat dan Kawasan Permukiman',
                'instansi' => 'Kepala Dinas Perumahan Rakyat dan Kawasan Permukiman',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/25.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'M.AINUL GUFRON, S.Sos., M.M.',
                'nip' => null,
                'jabatan_keterangan' => 'Kepala Dinas Perpustakaan dan Kearsipan',
                'instansi' => 'Kepala Dinas Perpustakaan dan Kearsipan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/26.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'MOH HASBULLAH',
                'nip' => null,
                'jabatan_keterangan' => 'Kepala Satuan Polisi Pamong Praja',
                'instansi' => 'Kepala Satuan Polisi Pamong Praja',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/27.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'RIZAL MORRIS, M.Si.',
                'nip' => '197409241993111002',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Penanaman Modal Dan Pelayanan Terpadu Satu Pintu',
                'instansi' => 'Kepala Dinas Penanaman Modal Dan Pelayanan Terpadu Satu Pintu',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/28.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'AHMAT HAFID, SE.,MM.',
                'nip' => '196901311990031003',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Badan Pengelolaan Keuangan dan Aset Daerah',
                'instansi' => 'Kepala Badan Pengelolaan Keuangan dan Aset Daerah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/29.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'AHMAT HAFID, SE.,MM.',
                'nip' => '196901311990031003',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Plt. Inspektur',
                'instansi' => 'Plt. Inspektur',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/30.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'RUDIYANTO, S.Sos., M.M.',
                'nip' => '197405131993021001',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Sekretaris DPRD',
                'instansi' => 'Sekretaris DPRD',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/31.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'JIMMY TRI SUKMANA',
                'nip' => null,
                'jabatan_keterangan' => 'Kepala Dinas Perindustrian dan Ketenagakerjaan',
                'instansi' => 'Kepala Dinas Perindustrian dan Ketenagakerjaan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/32.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'dr. NUNUK KRISTIANI Sp., Rad.',
                'nip' => '197010302002122003',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Kesehatan',
                'instansi' => 'Kepala Dinas Kesehatan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/33.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Badan',
                'nama' => 'ARI MURFIANTO, S.STP., M.Si.',
                'nip' => null,
                'jabatan_keterangan' => 'Kepala Badan Kepegawaian dan Sumber Daya Manusia',
                'instansi' => 'Kepala Badan Kepegawaian dan Sumber Daya Manusia',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/34.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Badan',
                'nama' => 'ARI MURFIANTO, S.STP., M.Si.',
                'nip' => null,
                'jabatan_keterangan' => 'Kepala Badan Kesatuan Bangsa dan Politik',
                'instansi' => 'Kepala Badan Kesatuan Bangsa dan Politik',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/35.jpg',
            ],
            [
                'kategori_pejabat' => 'Kepala Dinas',
                'nama' => 'MOCH MUSLEH, S.H., M.H',
                'nip' => '196810261994031005',
                'pangkat' => 'Pembina Utama Muda',
                'golongan' => 'IV/c',
                'jabatan_keterangan' => 'Kepala Dinas Pendidikan',
                'instansi' => 'Kepala Dinas Pendidikan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/36.jpg',
            ],
            [
                'kategori_pejabat' => 'Direktur RSUD',
                'nama' => 'dr. FARHAT SURYA NINGRAT, Sp.KK., FINSDV.',
                'nip' => null,
                'jabatan_keterangan' => 'Direktur RSUD Syarifah Ambami Rato Ebu',
                'instansi' => 'Direktur RSUD Syarifah Ambami Rato Ebu',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/37.jpg',
            ],
            [
                'kategori_pejabat' => 'Direktur',
                'nama' => 'H SJOBIRIN HASAN, S.E., MBA',
                'nip' => null,
                'jabatan_keterangan' => 'Dirut PUDAM Sumber Sejahtera',
                'instansi' => 'Dirut PUDAM Sumber Sejahtera',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/38.jpg',
            ],
            [
                'kategori_pejabat' => 'Direktur',
                'nama' => 'YUDHA ALIHAMSYAH, S.Sos., S.H.',
                'nip' => null,
                'jabatan_keterangan' => 'Dirut PT Sumber Daya',
                'instansi' => 'Dirut PT Sumber Daya',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/39.jpg',
            ],
            [
                'kategori_pejabat' => 'Direktur',
                'nama' => 'M. ACH. Slamet Utomo, BPA., S.E',
                'nip' => null,
                'jabatan_keterangan' => 'Dirut Perumda BPR',
                'instansi' => 'Dirut Perumda BPR',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/40.jpg',
            ],
            [
                'kategori_pejabat' => 'Lainnya',
                'nama' => 'MAHSUS, SAP',
                'nip' => '197107082002121007',
                'pangkat' => 'Penata Tingkat I',
                'golongan' => 'III/d',
                'jabatan_keterangan' => 'Camat Modung',
                'instansi' => 'Camat Modung',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/41.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'IMAM MAHFUD, SH., MM.',
                'nip' => '197307062006041011',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'jabatan_keterangan' => 'Camat Tanjung Bumi',
                'instansi' => 'Camat Tanjung Bumi',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/42.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'FAHROZY CHOIRIL ZAMZAM, S.STP., MM.',
                'nip' => '198707092006021001',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'jabatan_keterangan' => 'Camat Galis',
                'instansi' => 'Camat Galis',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/43.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'AINUL YAGIN, SE., MM.',
                'nip' => '196804131996021002',
                'pangkat' => 'Pembina Tingkat I',
                'golongan' => 'IV/b',
                'jabatan_keterangan' => 'Camat Kamal',
                'instansi' => 'Camat Kamal',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/44.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'OFIANDRI, M.Si.',
                'nip' => null,
                'jabatan_keterangan' => 'Camat Socah',
                'instansi' => 'Camat Socah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/45.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'FUAD ASYADAN, SH (Pensiun)',
                'nip' => '196805292006041003',
                'pangkat' => 'Penata Tingkat I',
                'golongan' => 'III/d',
                'jabatan_keterangan' => 'Camat Socah',
                'instansi' => 'Camat Socah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/46.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'ERWIN YOESOEF, SE., MM.',
                'nip' => '197905042006041021',
                'pangkat' => 'Pembina',
                'golongan' => 'IV/a',
                'jabatan_keterangan' => 'Camat Burneh',
                'instansi' => 'Camat Burneh',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/47.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'AHMADI SAFAR, SE.',
                'nip' => null,
                'jabatan_keterangan' => 'Camat Bangkalan',
                'instansi' => 'Camat Bangkalan',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/48.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'YAHYA ROCHMAN, SE, M.Ak.',
                'nip' => null,
                'jabatan_keterangan' => 'Camat Kokop',
                'instansi' => 'Camat Kokop',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/49.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'AMIR LUTFI, S.STP., M.Si.',
                'nip' => null,
                'jabatan_keterangan' => 'Camat Kwanyar',
                'instansi' => 'Camat Kwanyar',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/50.jpg',
            ],
            [
                'kategori_pejabat' => 'Camat',
                'nama' => 'AMIR LUTFI, S.STP., M.Si.',
                'nip' => null,
                'jabatan_keterangan' => 'Plt. Camat Tanah Merah',
                'instansi' => 'Plt. Camat Tanah Merah',
                'tempat_lahir' => null,
                'tanggal_lahir' => null,
                'riwayat_pendidikan' => null,
                'riwayat_karir' => null,
                'penghargaan' => null,
                'foto' => 'pejabat_fotos/51.jpg',
            ],
        ];

        foreach ($pejabats as $pejabat) {
            Pejabat::create($pejabat);
        }
    }
}
