<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Dokumen;
use App\Models\Opd;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;

class DokumenController extends Controller
{
    public function index()
    {
        $dokumens = Dokumen::with('opd')->latest()->paginate(10);
        return view('admin.dokumen.index', compact('dokumens'));
    }

    public function create()
    {
        $opds = Opd::orderBy('nama_opd')->get();
        return view('admin.dokumen.create', compact('opds'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'kategori' => 'required|in:SOP,Dasar Hukum',
            'judul' => 'required|string|max:255',
            'tahun' => 'required|integer',
            'opd_id' => 'required|exists:opds,id',
            'file' => 'required|mimes:pdf|max:10240', // max 10MB
            'keterangan' => 'nullable|string',
        ]);

        $file = $request->file('file');
        $filePath = $file->store('dokumens', 'public');
        $fileSize = $file->getSize();

        Dokumen::create([
            'kategori' => $request->kategori,
            'judul' => $request->judul,
            'slug' => Str::slug($request->judul) . '-' . time(),
            'tahun' => $request->tahun,
            'opd_id' => $request->opd_id,
            'file_path' => $filePath,
            'file_size' => $fileSize,
            'keterangan' => $request->keterangan,
        ]);

        return redirect()->route('admin.dokumen.index')->with('success', 'Dokumen berhasil ditambahkan.');
    }

    public function edit(Dokumen $dokuman) // parameter name based on singular 'dokuman' generated by laravel sometimes, let's fix it to $dokumen
    {
        $dokumen = $dokuman;
        $opds = Opd::orderBy('nama_opd')->get();
        return view('admin.dokumen.edit', compact('dokumen', 'opds'));
    }

    public function update(Request $request, Dokumen $dokuman)
    {
        $dokumen = $dokuman;
        $request->validate([
            'kategori' => 'required|in:SOP,Dasar Hukum',
            'judul' => 'required|string|max:255',
            'tahun' => 'required|integer',
            'opd_id' => 'required|exists:opds,id',
            'file' => 'nullable|mimes:pdf|max:10240',
            'keterangan' => 'nullable|string',
        ]);

        $data = [
            'kategori' => $request->kategori,
            'judul' => $request->judul,
            'tahun' => $request->tahun,
            'opd_id' => $request->opd_id,
            'keterangan' => $request->keterangan,
        ];

        if ($request->hasFile('file')) {
            if (Storage::disk('public')->exists($dokumen->file_path)) {
                Storage::disk('public')->delete($dokumen->file_path);
            }
            $file = $request->file('file');
            $data['file_path'] = $file->store('dokumens', 'public');
            $data['file_size'] = $file->getSize();
        }

        if ($dokumen->judul !== $request->judul) {
            $data['slug'] = Str::slug($request->judul) . '-' . time();
        }

        $dokumen->update($data);

        return redirect()->route('admin.dokumen.index')->with('success', 'Dokumen berhasil diperbarui.');
    }

    public function destroy(Dokumen $dokuman)
    {
        $dokumen = $dokuman;
        if (Storage::disk('public')->exists($dokumen->file_path)) {
            Storage::disk('public')->delete($dokumen->file_path);
        }
        $dokumen->delete();

        return redirect()->route('admin.dokumen.index')->with('success', 'Dokumen berhasil dihapus.');
    }
}
